[database]
HOST = localhost
USUARIO = root
PASSWORD = admin
NOMBRE_DB = bd_estacionamiento
PORT = 3306

[google]
# Pega aquí tu clave real de Gemini que me mostraste antes en el Word
API_KEY = AIzaSyDEecuyV6Icx3QWgL31N5KtOSyA7EiUVbQ
PROJECT_ID =